apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: devopsdozo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-role
  namespace: devopsdozo
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["deployments", "services", "pods", "jobs", "configmaps", "secrets", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-role-binding
  namespace: devopsdozo
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: devopsdozo
roleRef:
  kind: Role
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io