name: Render PlantUML

on:
  push:
    paths:
      - 'infrastructure/architecture.puml'
      - '.github/workflows/render-plantuml.yml'

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Render PlantUML to PNG
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" plantuml/plantuml:latest -tpng /workspace/infrastructure/architecture.puml

      - name: Commit rendered PNG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add infrastructure/architecture.png || true
          git commit -m "chore: render PlantUML diagram" || echo "No changes to commit"
          git push
